# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  # boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sata_nv" "usbhid" "usb_storage"  "zfs" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" "zfs"];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  # boot.loader.grub.device = "/dev/disk/by-id/ata-Samsung_SSD_840_EVO_250GB_S1DBNSAF757040Z";
  boot.loader.grub.device = "/dev/disk/by-id/ata-SPCC_Solid_State_Disk_BF330788145300060674";

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/ata-SPCC_Solid_State_Disk_BF330788145300060674-part1";
      fsType = "ext4";
    };

  fileSystems."/" =
    { device = "zesspool/ROOT";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zesspool/ROOT/home";
      fsType = "zfs";
    };

  # swapDevices =[ { label = "swap"; } ];

  nix.maxJobs = lib.mkDefault 8;
}
